site_name: CSC232 - Data Structures
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/professordaehn
      name: Professor Daehn on Twitter
copyright: Copyright &copy; 2022 James R. Daehn
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
