site_name: CSC232 - Data Structures
repo_url: https://github.com/msu-csc232-fa24/labs-manual
repo_name: msu-csc232-fa24/labs-manual
edit_uri: ""
nav:
  - Home: index.md
  - Review:
      - Basics:
        - Declarations: Review/cpp-rev-01.md
        - Arrays: Review/cpp-rev-02.md
  - Labs: "Labs/index.md"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.expand
#    - navigation.indexes
    - navigation.top
#    - navigation.instant
#    - navigation.tracking
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/professordaehn
      name: Professor Daehn on Twitter
copyright: Copyright &copy; 2022 James R. Daehn
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
