site_name: CSC232 - Data Structures
repo_url: https://github.com/msu-csc232/tddwcpp
repo_name: msu-csc232/tddwcpp
edit_uri: ""
nav:
  - Home: index.md
  - Syllabus:
      - CSC232:
        - Contact Info: syllabus.md
      - Useful Links: links.md
      - Help: links.md
  - Review:
      - Basics:
        - Declarations: Review/cpp-rev-01.md
        - Arrays: Review/cpp-rev-02.md
      - STL: Review/decl.md
  - Collections: "Collections/index.md"
  - Sorting Algorithms: "Sorting/index.md"
  - Lists: "Lists/index.md"
  - Sorted Lists: "SortedLists/index.md"
  - Stacks: "Stacks/index.md"
  - Queues: "Queues/index.md"
  - Priority Queues: "PriorityQueues/index.md"
  - Trees: "Trees/index.md"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.expand
#    - navigation.indexes
    - navigation.top
#    - navigation.instant
#    - navigation.tracking
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/professordaehn
      name: Professor Daehn on Twitter
copyright: Copyright &copy; 2022 James R. Daehn
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
