site_name: CSC232 - Data Structures
repo_url: https://github.com/msu-csc232/tddwcpp
repo_name: msu-csc232/tddwcpp
edit_uri: ""
nav:
  - Home: index.md
  - Syllabus:
      - Contact Info: syllabus.md
      - Useful Links: links.md
  - Review:
      - Basics:
        - Declarations: 01-Review/cpp-rev-01.md
        - Arrays: 01-Review/cpp-rev-02.md
      - STL: 01-Review/decl.md
  - Collections: "02-Collections/index.md"
  - Sorting Algorithms: "03-Sorting/index.md"
  - Lists: "04-Lists/index.md"
  - Sorted Lists: "05-SortedLists/index.md"
  - Stacks: "06-Stacks/index.md"
  - Queues: "07-Queues/index.md"
  - Priority Queues: "08-PriorityQueues/index.md"
  - Trees: "09-Trees/index.md"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/professordaehn
      name: Professor Daehn on Twitter
copyright: Copyright &copy; 2022 James R. Daehn
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
